#!/bin/bash
cd ~/flowstas/src

echo "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeXNwb2ZqYnFmend2bWtrdnZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NDcyODMsImV4cCI6MjA5MDQyMzI4M30.ov3sZSBdZJK8NrjoS5ktvTm_AZri01UA8l8KVtw4IPM" | vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production
echo "https://iryspofjbqfzwvmkkvvd.supabase.co" | vercel env add NEXT_PUBLIC_SUPABASE_URL production
echo "pk_live_51T6h6gKGCLdNId16FYfZvokMEDrpI1YLFMRKlFvE73DANZgnZrlDN7M2EcXrOPsFmxGgbJ1cPcLBUM7bpetZs3GG00sjpxWok7" | vercel env add NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY production
echo "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" | vercel env add STRIPE_SECRET_KEY production
echo "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeXNwb2ZqYnFmend2bWtrdnZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDg0NzI4MywiZXhwIjoyMDkwNDIzMjgzfQ.MwZzre55C4bi-U_mpkJGMgl89Q8EgcaXeDqZMHAJ-WU" | vercel env add SUPABASE_SERVICE_ROLE_KEY production
